name: Continuous Integration

on:
  workflow_dispatch:
  push:

jobs:
  build-release:
    strategy:
      matrix:
        # https://github.com/actions/virtual-environments
        os: [macos-12, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Check a Release build
        run: swift build --disable-automatic-resolution -c release

  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: fwal/setup-swift@v1
      - name: Run tests
        run: swift test
